[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4==4.13.4",
    "joblib==1.5.1",
    "nltk==3.9.1",
    "playwright==1.54.0",
    "tqdm==4.67.1",
]
